#!/usr/bin/env bash

set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RESOLVER="$ROOT/cbs/stack/stack_resolver.sh"

fail() {
    echo "TEST_STACK_RESOURCE_RESOLUTION_RESULT=FAIL" >&2
    echo "TEST_STACK_RESOURCE_RESOLUTION_FAILURE=$1" >&2
    return 1
}

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

MANIFEST="$TMP/stack.env"

cat > "$MANIFEST" <<'MANIFEST'
CBS_STACK_ID=classification-test
CBS_STACK_VERSION=1

CBS_STACK_PREREQUISITE_GIT=REQUIRED

CBS_STACK_MANAGED_TOOLCHAIN_IDS=SDK
CBS_STACK_MANAGED_TOOLCHAIN_SDK_REQUIREMENT=REQUIRED
CBS_STACK_MANAGED_TOOLCHAIN_SDK_VERSION=1.2.3
CBS_STACK_MANAGED_TOOLCHAIN_SDK_PROVIDER=synthetic

CBS_STACK_PROJECT_DEPENDENCY_IDS=APP_PACKAGE
CBS_STACK_PROJECT_DEPENDENCY_APP_PACKAGE_REQUIREMENT=REQUIRED
CBS_STACK_PROJECT_DEPENDENCY_APP_PACKAGE_VERSION=4.5.6

CBS_STACK_COMPONENT_DATABASE=REQUIRED

CBS_STACK_MANIFEST_CAPABILITY_CHECK=check
MANIFEST

OUTPUT="$("$RESOLVER" "$MANIFEST")"

printf '%s\n' '--- SYSTEM_PREREQUISITE ---'

grep -A4 -F \
    'CBS_STACK_RESOURCE_TYPE=SYSTEM_PREREQUISITE' \
    <<<"$OUTPUT" |
    grep -Fq 'CBS_STACK_PREREQUISITE_NAME=GIT' ||
    fail "SYSTEM_PREREQUISITE"

echo "TEST_STACK_RESOURCE_RESOLUTION_SYSTEM_PREREQUISITE=PASS"

printf '%s\n' '--- MANAGED_TOOLCHAIN ---'

grep -A5 -F \
    'CBS_STACK_RESOURCE_TYPE=MANAGED_TOOLCHAIN' \
    <<<"$OUTPUT" |
    grep -Fq 'CBS_STACK_MANAGED_TOOLCHAIN_ID=SDK' ||
    fail "MANAGED_TOOLCHAIN"

grep -Fq \
    'CBS_STACK_MANAGED_TOOLCHAIN_VERSION=1.2.3' \
    <<<"$OUTPUT" ||
    fail "MANAGED_TOOLCHAIN_VERSION"

grep -Fq \
    'CBS_STACK_MANAGED_TOOLCHAIN_PROVIDER=synthetic' \
    <<<"$OUTPUT" ||
    fail "MANAGED_TOOLCHAIN_PROVIDER"

echo "TEST_STACK_RESOURCE_RESOLUTION_MANAGED_TOOLCHAIN=PASS"

printf '%s\n' '--- PROJECT_DEPENDENCY ---'

grep -A4 -F \
    'CBS_STACK_RESOURCE_TYPE=PROJECT_DEPENDENCY' \
    <<<"$OUTPUT" |
    grep -Fq 'CBS_STACK_PROJECT_DEPENDENCY_ID=APP_PACKAGE' ||
    fail "PROJECT_DEPENDENCY"

grep -Fq \
    'CBS_STACK_PROJECT_DEPENDENCY_VERSION=4.5.6' \
    <<<"$OUTPUT" ||
    fail "PROJECT_DEPENDENCY_VERSION"

echo "TEST_STACK_RESOURCE_RESOLUTION_PROJECT_DEPENDENCY=PASS"

printf '%s\n' '--- RUNTIME_COMPONENT ---'

grep -A4 -F \
    'CBS_STACK_RESOURCE_TYPE=RUNTIME_COMPONENT' \
    <<<"$OUTPUT" |
    grep -Fq 'CBS_STACK_COMPONENT_NAME=DATABASE' ||
    fail "RUNTIME_COMPONENT"

echo "TEST_STACK_RESOURCE_RESOLUTION_RUNTIME_COMPONENT=PASS"

printf '%s\n' '--- PLATFORM_CAPABILITY ---'

grep -A3 -F \
    'CBS_STACK_RESOURCE_TYPE=PLATFORM_CAPABILITY' \
    <<<"$OUTPUT" |
    grep -Fq 'CBS_STACK_CAPABILITY=check' ||
    fail "PLATFORM_CAPABILITY"

echo "TEST_STACK_RESOURCE_RESOLUTION_PLATFORM_CAPABILITY=PASS"

printf '%s\n' '--- LEGACY OUTPUTS PRESERVED ---'

grep -Fq 'CBS_STACK_PREREQUISITE_NAME=GIT' <<<"$OUTPUT" ||
    fail "LEGACY_PREREQUISITE"

grep -Fq 'CBS_STACK_COMPONENT_NAME=DATABASE' <<<"$OUTPUT" ||
    fail "LEGACY_COMPONENT"

grep -Fq 'CBS_STACK_CAPABILITY=check' <<<"$OUTPUT" ||
    fail "LEGACY_CAPABILITY"

echo "TEST_STACK_RESOURCE_RESOLUTION_LEGACY_COMPATIBILITY=PASS"

echo "TEST_STACK_RESOURCE_RESOLUTION_RESULT=PASS"
