#!/usr/bin/env bash

set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$ROOT/stacks/core-platform/stack.env"

fail() {
    echo "TEST_CORE_PLATFORM_STACK_MANIFEST_RESULT=FAIL" >&2
    echo "TEST_CORE_PLATFORM_STACK_MANIFEST_FAILURE=$1" >&2
    exit 1
}

[[ -f "$MANIFEST" ]] ||
    fail "MANIFEST_MISSING"

set -a
source "$MANIFEST"
set +a

[[ "$CBS_STACK_ID" == "core-platform" ]] ||
    fail "STACK_ID"

[[ "$CBS_STACK_VERSION" == "1" ]] ||
    fail "STACK_VERSION"

[[ "$CBS_STACK_PYTHON_VERSION" == "3.12" ]] ||
    fail "PYTHON_VERSION"

for value in \
    "$CBS_STACK_PREREQUISITE_GIT" \
    "$CBS_STACK_PREREQUISITE_UV" \
    "$CBS_STACK_PREREQUISITE_DOCKER" \
    "$CBS_STACK_PREREQUISITE_DOCKER_COMPOSE" \
    "$CBS_STACK_PREREQUISITE_PYTHON_312"
do
    [[ "$value" == "REQUIRED" ]] ||
        fail "PREREQUISITE_REQUIREMENT"
done

echo "TEST_CORE_PLATFORM_STACK_MANIFEST_PREREQUISITES=PASS"

for value in \
    "$CBS_STACK_COMPONENT_FASTAPI" \
    "$CBS_STACK_COMPONENT_SQLALCHEMY" \
    "$CBS_STACK_COMPONENT_ALEMBIC" \
    "$CBS_STACK_COMPONENT_POSTGRESQL" \
    "$CBS_STACK_COMPONENT_POSTGIS" \
    "$CBS_STACK_COMPONENT_PGVECTOR" \
    "$CBS_STACK_COMPONENT_REDIS" \
    "$CBS_STACK_COMPONENT_OPENSEARCH" \
    "$CBS_STACK_COMPONENT_KONG" \
    "$CBS_STACK_COMPONENT_KEYCLOAK"
do
    [[ "$value" == "REQUIRED" ]] ||
        fail "COMPONENT_REQUIREMENT"
done

echo "TEST_CORE_PLATFORM_STACK_MANIFEST_COMPONENTS=PASS"

[[ "$CBS_STACK_MANIFEST_CAPABILITY_START" == "start" ]]
[[ "$CBS_STACK_MANIFEST_CAPABILITY_CHECK" == "check" ]]
[[ "$CBS_STACK_MANIFEST_CAPABILITY_STATUS" == "status" ]]
[[ "$CBS_STACK_MANIFEST_CAPABILITY_QUALIFY" == "qualify" ]]

echo "TEST_CORE_PLATFORM_STACK_MANIFEST_CAPABILITIES=PASS"

echo "TEST_CORE_PLATFORM_STACK_MANIFEST_RESULT=PASS"
