#!/usr/bin/env bash

set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHECKER="$ROOT/cbs/workstation/prerequisite_checker.sh"
CONTRACT="$ROOT/cbs/workstation/contract.sh"

fail() {
    echo "TEST_PREREQUISITE_RESULT=FAIL" >&2
    echo "TEST_PREREQUISITE_FAILURE=$1" >&2
    exit 1
}

source "$CONTRACT"
source "$CHECKER"

OUTPUT="$("$CHECKER")"

grep -Fq 'CBS_PREREQUISITE_NAME=GIT' <<<"$OUTPUT" ||
    fail "GIT_NOT_CHECKED"

grep -Fq 'CBS_PREREQUISITE_NAME=SSH' <<<"$OUTPUT" ||
    fail "SSH_NOT_CHECKED"

grep -Fq 'CBS_PREREQUISITE_NAME=CURL' <<<"$OUTPUT" ||
    fail "CURL_NOT_CHECKED"

grep -Fq 'CBS_PREREQUISITE_NAME=DOCKER' <<<"$OUTPUT" ||
    fail "DOCKER_NOT_CHECKED"

grep -Fq 'CBS_PREREQUISITE_NAME=UV' <<<"$OUTPUT" ||
    fail "UV_NOT_CHECKED"

grep -Fq 'CBS_PREREQUISITE_NAME=DOCKER_ENGINE' <<<"$OUTPUT" ||
    fail "DOCKER_ENGINE_NOT_CHECKED"

grep -Fq 'CBS_PREREQUISITE_NAME=DOCKER_COMPOSE' <<<"$OUTPUT" ||
    fail "DOCKER_COMPOSE_NOT_CHECKED"

grep -Fq 'CBS_PREREQUISITE_NAME=PYTHON_312' <<<"$OUTPUT" ||
    fail "PYTHON_312_NOT_CHECKED"

grep -Fq 'CBS_PREREQUISITE_REQUIRED_FAILURES=0' <<<"$OUTPUT" ||
    fail "UNEXPECTED_FAILURE"

grep -Fq 'CBS_PREREQUISITE_RESULT=PASS' <<<"$OUTPUT" ||
    fail "RESULT_NOT_PASS"

echo "TEST_PREREQUISITE_COMMANDS=PASS"
echo "TEST_PREREQUISITE_DOCKER_ENGINE=PASS"
echo "TEST_PREREQUISITE_DOCKER_COMPOSE=PASS"
echo "TEST_PREREQUISITE_PYTHON_312=PASS"
echo "TEST_PREREQUISITE_AGGREGATION=PASS"
echo "TEST_PREREQUISITE_RESULT=PASS"
