#!/usr/bin/env bash

set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$ROOT/stacks/flutter/stack.env"
EVALUATOR="$ROOT/cbs/stack/stack_toolchain_evaluator.sh"

fail() {
    echo "TEST_FLUTTER_STACK_MANIFEST_RESULT=FAIL" >&2
    echo "TEST_FLUTTER_STACK_MANIFEST_FAILURE=$1" >&2
    return 1
}

[[ -f "$MANIFEST" ]] ||
    fail "MANIFEST_MISSING"

set -a
source "$MANIFEST"
set +a

[[ "$CBS_STACK_ID" == "flutter" ]] ||
    fail "STACK_ID"

[[ "$CBS_STACK_VERSION" == "1" ]] ||
    fail "STACK_VERSION"

[[ "$CBS_STACK_MANAGED_TOOLCHAIN_IDS" == "FLUTTER ANDROID_SDK XCODE" ]] ||
    fail "TOOLCHAIN_IDS"

[[ "$CBS_STACK_MANAGED_TOOLCHAIN_FLUTTER_REQUIREMENT" == "REQUIRED" ]] ||
    fail "TOOLCHAIN_REQUIREMENT"

[[ "$CBS_STACK_MANAGED_TOOLCHAIN_FLUTTER_VERSION" == "3.47.6" ]] ||
    fail "TOOLCHAIN_VERSION"

[[ "$CBS_STACK_MANAGED_TOOLCHAIN_FLUTTER_PROVIDER" == "flutter" ]] ||
    fail "TOOLCHAIN_PROVIDER"

echo "TEST_FLUTTER_STACK_MANIFEST_DECLARATION=PASS"


printf '%s\n' '--- ANDROID SDK DECLARATION ---'

[[ "${CBS_STACK_MANAGED_TOOLCHAIN_IDS:-}" == *"ANDROID_SDK"* ]] ||
    fail "ANDROID_SDK_ID"

[[ "${CBS_STACK_MANAGED_TOOLCHAIN_ANDROID_SDK_REQUIREMENT:-}" == "REQUIRED" ]] ||
    fail "ANDROID_SDK_REQUIREMENT"


[[ "${CBS_STACK_MANAGED_TOOLCHAIN_ANDROID_SDK_ID:-}" == "android-sdk" ]] ||
    fail "ANDROID_SDK_TOOLCHAIN_ID"

[[ "${CBS_STACK_MANAGED_TOOLCHAIN_ANDROID_SDK_VERSION:-}" == "36" ]] ||
    fail "ANDROID_SDK_VERSION"

[[ "${CBS_STACK_MANAGED_TOOLCHAIN_ANDROID_SDK_PROVIDER:-}" == "android-sdk" ]] ||
    fail "ANDROID_SDK_PROVIDER"

echo "TEST_FLUTTER_STACK_MANIFEST_ANDROID_SDK_DECLARATION=PASS"


printf '%s\n' '--- XCODE DECLARATION ---'

[[ "${CBS_STACK_MANAGED_TOOLCHAIN_IDS:-}" == *"XCODE"* ]] ||
    fail "XCODE_ID"

[[ "${CBS_STACK_MANAGED_TOOLCHAIN_XCODE_REQUIREMENT:-}" == "REQUIRED" ]] ||
    fail "XCODE_REQUIREMENT"

[[ "${CBS_STACK_MANAGED_TOOLCHAIN_XCODE_ID:-}" == "xcode" ]] ||
    fail "XCODE_TOOLCHAIN_ID"

[[ "${CBS_STACK_MANAGED_TOOLCHAIN_XCODE_VERSION:-}" == "15" ]] ||
    fail "XCODE_VERSION"

[[ "${CBS_STACK_MANAGED_TOOLCHAIN_XCODE_PROVIDER:-}" == "xcode" ]] ||
    fail "XCODE_PROVIDER"

echo "TEST_FLUTTER_STACK_MANIFEST_XCODE_DECLARATION=PASS"

[[ "${CBS_STACK_COMPONENT_ANDROID_EMULATOR:-}" == "OPTIONAL" ]] ||
    fail "ANDROID_EMULATOR_COMPONENT_REQUIREMENT"

echo "TEST_FLUTTER_STACK_MANIFEST_ANDROID_EMULATOR_COMPONENT=PASS"

OUTPUT="$(
    CBS_TOOLCHAIN_ROOT="$HOME/.cbs/toolchains" \
    "$EVALUATOR" "$MANIFEST"
)"

grep -Fq \
    'CBS_STACK_RESOURCE_TYPE=MANAGED_TOOLCHAIN' \
    <<<"$OUTPUT" ||
    fail "RESOURCE_TYPE"

grep -Fq \
    'CBS_STACK_MANAGED_TOOLCHAIN_ID=FLUTTER' \
    <<<"$OUTPUT" ||
    fail "TOOLCHAIN_ID"

grep -Fq \
    'CBS_STACK_MANAGED_TOOLCHAIN_INSTALLATION_STATE=PRESENT_COMPATIBLE' \
    <<<"$OUTPUT" ||
    fail "INSTALLATION_STATE"

grep -Fq \
    'CBS_STACK_MANAGED_TOOLCHAIN_DECISION=REUSE' \
    <<<"$OUTPUT" ||
    fail "REUSE_DECISION"

grep -Fq \
    'CBS_STACK_MANAGED_TOOLCHAIN_MUTATION=NONE' \
    <<<"$OUTPUT" ||
    fail "READ_ONLY"

grep -Fq \
    'CBS_STACK_TOOLCHAIN_REQUIRED_COUNT=3' \
    <<<"$OUTPUT" ||
    fail "REQUIRED_COUNT"

grep -Fq \
    'CBS_STACK_TOOLCHAIN_MISSING_COUNT=0' \
    <<<"$OUTPUT" ||
    fail "MISSING_COUNT"


grep -Fq \
    'CBS_STACK_TOOLCHAIN_NOT_APPLICABLE_COUNT=1' \
    <<<"$OUTPUT" ||
    fail "NOT_APPLICABLE_COUNT"

grep -Fq \
    'CBS_STACK_TOOLCHAIN_EVALUATION_RESULT=PASS' \
    <<<"$OUTPUT" ||
    fail "RESULT"

echo "TEST_FLUTTER_STACK_MANIFEST_REAL_REUSE=PASS"

echo "TEST_FLUTTER_STACK_MANIFEST_RESULT=PASS"
