#!/usr/bin/env bash

if [[ "${CBS_STACK_RESOURCE_CONTRACT_LOADED:-0}" == "1" ]]; then
    return 0 2>/dev/null || true
fi

CBS_STACK_RESOURCE_CONTRACT_LOADED=1
readonly CBS_STACK_RESOURCE_CONTRACT_LOADED

CBS_STACK_RESOURCE_CONTRACT_VERSION=1
readonly CBS_STACK_RESOURCE_CONTRACT_VERSION

readonly CBS_STACK_RESOURCE_TYPE_SYSTEM_PREREQUISITE="SYSTEM_PREREQUISITE"
readonly CBS_STACK_RESOURCE_TYPE_MANAGED_TOOLCHAIN="MANAGED_TOOLCHAIN"
readonly CBS_STACK_RESOURCE_TYPE_PROJECT_DEPENDENCY="PROJECT_DEPENDENCY"
readonly CBS_STACK_RESOURCE_TYPE_RUNTIME_COMPONENT="RUNTIME_COMPONENT"
readonly CBS_STACK_RESOURCE_TYPE_PLATFORM_CAPABILITY="PLATFORM_CAPABILITY"

cbs_stack_resource_type_is_valid() {
    case "${1:-}" in
        "$CBS_STACK_RESOURCE_TYPE_SYSTEM_PREREQUISITE"|\
        "$CBS_STACK_RESOURCE_TYPE_MANAGED_TOOLCHAIN"|\
        "$CBS_STACK_RESOURCE_TYPE_PROJECT_DEPENDENCY"|\
        "$CBS_STACK_RESOURCE_TYPE_RUNTIME_COMPONENT"|\
        "$CBS_STACK_RESOURCE_TYPE_PLATFORM_CAPABILITY")
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}
